### ISSUE TITLE
Config doesn't work

### ISSUE THREAD

**Issue by Venemo** [deian/git-ssh-server#2]
I get an error when running `git-ssh-server config myssh_conf`. Here is the terminal output:

```
$ git-ssh-server config myssh_conf

/usr/lib/node_modules/git-ssh-server/lib/git-ssh-server.js:29
  if (!util.isString(config_dir)) {
            ^
TypeError: Object #<Object> has no method 'isString'
    at new GitSshServer (/usr/lib/node_modules/git-ssh-server/lib/git-ssh-server.js:29:13)
    at Object.<anonymous> (/usr/lib/node_modules/git-ssh-server/bin/git-ssh-server.js:44:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by Venemo** [comment]
Forgot to mention: I'm running on node v0.10.36

**Comment by Venemo** [comment]
After replacing all occourences of `isString`, `isFunction` and `isUndefined` with the typeof keyword, it seems to work.

**Comment by deian** [comment]
Sorry, I didn't get an email about this. Can you give it a shot with https://www.npmjs.com/package/util-is and if it works send me a PR?

**Comment by deian** [comment]
Though I'm honestly okay with using `typeof` as well; so send PR :)

**Comment by Venemo** [comment]
I simply used string replace to find all occourences. At the end, I didn't manage to get it working (sshd never accepted my public keys) and after a while I gave up and deleted my clone of your repo. So I'm sorry, but I no longer have the code.

**Comment by deian** [comment]
No worries. Sorry to hear that things didn't work out.
